---
# builds 2 images from dockerfiles
# creates 2 containers on one host for 1 master and 1 slave database using docker-compose
# can be used in staging, qa, test or development environment

# here are no ports to db exposed, which is optional anyway

- name: docker_compose | Copy docker_compose project directory
  copy: 
    src: db_replication
    dest: "{{ docker_compose_project_path }}"
    mode: u=rw,g=r,o=r
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: docker_compose | Transfer Template .env file 
  template:
    src: .env.j2
    dest: "{{ docker_compose_project_path }}/db_replication/.env"
    mode: u=rw,g=r,o=r
    owner: "{{ target_user }}"
    group: "{{ target_user }}"


- name: docker_compose | Create and start services, this can take a while...
  docker_compose:
    project_src: "{{ docker_compose_project_path }}/db_replication"
    build: yes
  register: service_status

- name: docker_compose | debug service status
  debug: msg={{ service_status }}


